- name: copy new index.html
  hosts: centos8

  tasks:
    - name: install httpd
      yum: name=httpd

    - name: copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web
  
  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted